/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReachUsRouteImport } from './routes/reach-us'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CommunitySlugRouteImport } from './routes/community.$slug'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as TaxonomySlugRouteImport } from './routes/taxonomy.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReachUsRoute = ReachUsRouteImport.update({
  id: '/reach-us',
  path: '/reach-us',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CommunitySlugRoute = CommunitySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CommunityRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxonomySlugRoute = TaxonomySlugRouteImport.update({
  id: '/taxonomy/$slug',
  path: '/taxonomy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/community': typeof CommunityRouteWithChildren
  '/experiences': typeof ExperiencesRoute
  '/privacy': typeof PrivacyRoute
  '/reach-us': typeof ReachUsRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/users': typeof AdminUsersRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/taxonomy/$slug': typeof TaxonomySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRouteWithChildren
  '/experiences': typeof ExperiencesRoute
  '/privacy': typeof PrivacyRoute
  '/reach-us': typeof ReachUsRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/users': typeof AdminUsersRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/taxonomy/$slug': typeof TaxonomySlugRoute
  '/admin': typeof AdminIndexRoute
  '/journal': typeof JournalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/community': typeof CommunityRouteWithChildren
  '/experiences': typeof ExperiencesRoute
  '/privacy': typeof PrivacyRoute
  '/reach-us': typeof ReachUsRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/users': typeof AdminUsersRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/taxonomy/$slug': typeof TaxonomySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/community'
    | '/experiences'
    | '/privacy'
    | '/reach-us'
    | '/studio'
    | '/terms'
    | '/tools'
    | '/admin/login'
    | '/admin/newsletter'
    | '/admin/posts'
    | '/admin/users'
    | '/community/$slug'
    | '/journal/$slug'
    | '/taxonomy/$slug'
    | '/admin/'
    | '/journal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community'
    | '/experiences'
    | '/privacy'
    | '/reach-us'
    | '/studio'
    | '/terms'
    | '/tools'
    | '/admin/login'
    | '/admin/newsletter'
    | '/admin/posts'
    | '/admin/users'
    | '/community/$slug'
    | '/journal/$slug'
    | '/taxonomy/$slug'
    | '/admin'
    | '/journal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/community'
    | '/experiences'
    | '/privacy'
    | '/reach-us'
    | '/studio'
    | '/terms'
    | '/tools'
    | '/admin/login'
    | '/admin/newsletter'
    | '/admin/posts'
    | '/admin/users'
    | '/community/$slug'
    | '/journal/$slug'
    | '/taxonomy/$slug'
    | '/admin/'
    | '/journal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CommunityRoute: typeof CommunityRouteWithChildren
  ExperiencesRoute: typeof ExperiencesRoute
  PrivacyRoute: typeof PrivacyRoute
  ReachUsRoute: typeof ReachUsRoute
  StudioRoute: typeof StudioRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRoute
  JournalSlugRoute: typeof JournalSlugRoute
  TaxonomySlugRoute: typeof TaxonomySlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reach-us': {
      id: '/reach-us'
      path: '/reach-us'
      fullPath: '/reach-us'
      preLoaderRoute: typeof ReachUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/community/$slug': {
      id: '/community/$slug'
      path: '/$slug'
      fullPath: '/community/$slug'
      preLoaderRoute: typeof CommunitySlugRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxonomy/$slug': {
      id: '/taxonomy/$slug'
      path: '/taxonomy/$slug'
      fullPath: '/taxonomy/$slug'
      preLoaderRoute: typeof TaxonomySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CommunityRouteChildren {
  CommunitySlugRoute: typeof CommunitySlugRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunitySlugRoute: CommunitySlugRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CommunityRoute: CommunityRouteWithChildren,
  ExperiencesRoute: ExperiencesRoute,
  PrivacyRoute: PrivacyRoute,
  ReachUsRoute: ReachUsRoute,
  StudioRoute: StudioRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRoute,
  JournalSlugRoute: JournalSlugRoute,
  TaxonomySlugRoute: TaxonomySlugRoute,
  JournalIndexRoute: JournalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
