/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ReachUsRouteImport } from './routes/reach-us'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as TaxonomySlugRouteImport } from './routes/taxonomy.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ReachUsRoute = ReachUsRouteImport.update({
  id: '/reach-us',
  path: '/reach-us',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxonomySlugRoute = TaxonomySlugRouteImport.update({
  id: '/taxonomy/$slug',
  path: '/taxonomy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/reach-us': typeof ReachUsRoute
  '/studio': typeof StudioRoute
  '/tools': typeof ToolsRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/taxonomy/$slug': typeof TaxonomySlugRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/reach-us': typeof ReachUsRoute
  '/studio': typeof StudioRoute
  '/tools': typeof ToolsRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/taxonomy/$slug': typeof TaxonomySlugRoute
  '/journal': typeof JournalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/reach-us': typeof ReachUsRoute
  '/studio': typeof StudioRoute
  '/tools': typeof ToolsRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/taxonomy/$slug': typeof TaxonomySlugRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/reach-us'
    | '/studio'
    | '/tools'
    | '/journal/$slug'
    | '/taxonomy/$slug'
    | '/journal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/reach-us'
    | '/studio'
    | '/tools'
    | '/journal/$slug'
    | '/taxonomy/$slug'
    | '/journal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/reach-us'
    | '/studio'
    | '/tools'
    | '/journal/$slug'
    | '/taxonomy/$slug'
    | '/journal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ReachUsRoute: typeof ReachUsRoute
  StudioRoute: typeof StudioRoute
  ToolsRoute: typeof ToolsRoute
  JournalSlugRoute: typeof JournalSlugRoute
  TaxonomySlugRoute: typeof TaxonomySlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reach-us': {
      id: '/reach-us'
      path: '/reach-us'
      fullPath: '/reach-us'
      preLoaderRoute: typeof ReachUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxonomy/$slug': {
      id: '/taxonomy/$slug'
      path: '/taxonomy/$slug'
      fullPath: '/taxonomy/$slug'
      preLoaderRoute: typeof TaxonomySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ReachUsRoute: ReachUsRoute,
  StudioRoute: StudioRoute,
  ToolsRoute: ToolsRoute,
  JournalSlugRoute: JournalSlugRoute,
  TaxonomySlugRoute: TaxonomySlugRoute,
  JournalIndexRoute: JournalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
